<a href="https://colab.research.google.com/github/jidnyasaBhoir/Sentiment-Analysis-using-Bert-hugging-face/blob/main/sentiment_analysis_with_bert_hugging_face.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Transformers installation
!pip install transformers

Transformers library features. The library downloads pretrained models for Natural Language Understanding (NLU) tasks, such as analyzing the sentiment of a text, and Natural Language Generation (NLG), such as completing a prompt with new text or translating in another language.


 Transformers provides the following tasks out of the box:

Sentiment analysis: is a text positive or negative?

Text generation (in English): provide a prompt and the model will generate what follows.

Name entity recognition (NER): in an input sentence, label each word with the entity it represents (person, place, etc.)

Question answering: provide the model with some context and a question, extract the answer from the context.

Filling masked text: given a text with masked words (e.g., replaced by [MASK]), fill the blanks.

Summarization: generate a summary of a long text.

Translation: translate a text in another language.

Feature extraction: return a tensor representation of the text.

Let's see how this work for sentiment analysis

In [2]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

A pretrained model and its tokenizer are downloaded and cached.
By default, the model downloaded for this pipeline is called "distilbert-base-uncased-finetuned-sst-2-english

In [3]:
classifier('We are very happy to show you the 🤗 Transformers library.')

[{'label': 'POSITIVE', 'score': 0.9997795224189758}]

In [4]:
classifier('The pizza is not that great but the crust is awesome.')

[{'label': 'POSITIVE', 'score': 0.9998461008071899}]

In [6]:
results = classifier(["We are very happy to show you the 🤗 Transformers library.",
           "We hope you don't hate it."])
for result in results:
  print(f"label:{result['label']}, with score:{round(result['score'],4)}")

label:POSITIVE, with score:0.9998
label:NEGATIVE, with score:0.5309


In [7]:
classifier = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [8]:
classifier("Esperamos que no lo odie.")

[{'label': '3 stars', 'score': 0.3368820250034332}]

This classifier can now deal with texts in English, French, but also Dutch, German, Italian and Spanish!

In [26]:
from transformers import AutoTokenizer, BertForSequenceClassification

AutoTokenizer, which we will use to download the tokenizer associated to the model we picked and instantiate it. The second is AutoModelForSequenceClassification (or TFAutoModelForSequenceClassification or BertForSequenceClassification if you are using TensorFlow), which we will use to download the model itself.

In [49]:
model= "nlptown/bert-base-multilingual-uncased-sentiment"
tf_model = BertForSequenceClassification.from_pretrained(model)
tokenizer = AutoTokenizer.from_pretrained("nlptown/bert-base-multilingual-uncased-sentiment")
classifier = pipeline('sentiment-analysis', model=tf_model, tokenizer= tokenizer)

In [50]:
classifier("I am a good girl")

[{'label': '4 stars', 'score': 0.41006219387054443}]

In [51]:
input = tokenizer("I am the best")

In [32]:
print(input)

{'input_ids': [101, 151, 10345, 10103, 11146, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1]}


In [38]:
for key,value in tf_batch.items():
  print(f"{key}:{value.numpy().tolist()}")

input_ids:[[101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 100, 58263, 13299, 119, 102], [101, 11312, 18763, 10855, 11530, 112, 162, 39487, 10197, 119, 102, 0, 0, 0]]
token_type_ids:[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask:[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]


In [52]:
tf_batch = tokenizer( ["We are very happy to show you the 🤗 Transformers library.", "We hope you don't hate it."],
                    truncation= True,
                     padding = True,
                     max_length = 512,
                     return_tensors='tf'


)

In [61]:
for key, value in tf_batch.items():
    print(f"{key}: {value.numpy().tolist()}")

input_ids: [[101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103, 100, 58263, 13299, 119, 102], [101, 11312, 18763, 10855, 11530, 112, 162, 39487, 10197, 119, 102, 0, 0, 0]]
token_type_ids: [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]]


In [60]:
print(tf_batch)

{'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101, 11312, 10320, 12495, 19308, 10114, 11391, 10855, 10103,
          100, 58263, 13299,   119,   102],
       [  101, 11312, 18763, 10855, 11530,   112,   162, 39487, 10197,
          119,   102,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]], dtype=int32)>}


Here we use the predefined vocabulary of DistilBERT (hence load the tokenizer with the DistilBertTokenizer.from_pretrained method) and initialize the model.

In [59]:
from transformers import DistilBertConfig, DistilBertTokenizer, TFDistilBertForSequenceClassification
config = DistilBertConfig(n_heads=8, dim=512, hidden_dim=4*512)
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = TFDistilBertForSequenceClassification(config)

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]